CREATE DATABASE empresa
DEFAULT CHARSET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

USE empresa;

CREATE TABLE clientes(
id_cliente INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
nome VARCHAR (60) NOT NULL,
username VARCHAR (30) NULL,
aniversario DATE NULL,
email VARCHAR(60) NOT NULL,
senha VARCHAR(30) NOT NULL,
celular VARCHAR(16) NOT NULL,
telefone VARCHAR (16) NULL 
);

CREATE TABLE amigos(
id_amigo INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
nome VARCHAR (60) NOT NULL,
username VARCHAR (30) NULL,
aniversario DATE NULL,
email VARCHAR (60) NOT NULL,
celular VARCHAR (16) NOT NULL,
telefone VARCHAR (16) NULL,
fk_id_cliente INTEGER NOT NULL
);

ALTER TABLE amigos ADD CONSTRAINT fk_id_cliente FOREIGN KEY (fk_id_cliente) REFERENCES clientes (id_cliente);




